name: Docker Image CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: docker login
      env:
        DOCKER_USER: ${{secrets.DOCKER_USER}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_PASSWORD
    - name: Build the php 7.4 Docker image
      run: docker build ./7.4 -t oracle-php -t oracle-php:7.4 -t ${{secrets.DOCKER_USER}}/oracle-php:7.4
    - name: Build the php 8.0 Docker image
      run: docker build ./8.0 -t oracle-php -t oracle-php:7.4 -t ${{secrets.DOCKER_USER}}/oracle-php:8.0
    - name: Push 7.4
      run: docker push ${{secrets.DOCKER_USER}}/oracle-php:7.4
    - name: Push 8.0
      run: docker push ${{secrets.DOCKER_USER}}/oracle-php:8.0
